version: '3.2'
services:
  blaze:
    image: "samply/blaze:0.17"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      LOG_LEVEL: "debug"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
volumes:
  blaze-data:
